# Generated by Django 5.0.7 on 2024-08-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_adders',
            field=models.TextField(default='default title', max_length=300, verbose_name='Ссылка на сайт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=50, verbose_name='Текст объявления'),
        ),
    ]
