# Generated by Django 5.0.7 on 2024-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_url_adders_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_adders',
            field=models.TextField(max_length=150, verbose_name='Ссылка на сайт'),
        ),
    ]
