# Generated by Django 5.0.7 on 2024-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_text_alter_post_url_adders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_adders',
            field=models.CharField(max_length=150, verbose_name='Ссылка на сайт'),
        ),
    ]
